#!/usr/bin/env bash

set -euo pipefail

run_or_fail() {
    local error_msg="$1"
    shift
    if ! "$@" ; then
        echo "$error_msg"
        exit 1
    fi
}

ask() {
    read -p "$1 (y/n)? " ANSWER < /dev/tty
    [[ "$ANSWER" == "y" ]]
}

if [ "$EUID" -eq 0 ] && ! ask "Was running this script as root intentional"; then
  exit
fi

echo "=== Setup ==="

# Install yay

if ! command -v yay > /dev/null; then
    git clone https://aur.archlinux.org/yay.git "/tmp/yay"
    pushd /tmp/yay
    makepkg -si --noconfirm --clean --cleanbuild --rmdeps
    popd
    rm -rf /tmp/yay
fi

if ask "Setup Git"; then
    echo "=== Git ==="

    git config --global user.email "pvsakith@gmail.com"
    git config --global user.name "Sakith B."

    echo "=== Git complete ==="
fi

if ask "Setup GPG and SSH"; then
    echo "=== SSH and GPG ==="

    sudo pacman -S openssh opengpg --needed --noconfirm

	echo "--------------------------------------------------------"
    echo "PASTE ED25519 PRIVATE KEY BELOW"
    echo "(Press Enter, paste the key, press Enter, then Ctrl+D)"
    echo "--------------------------------------------------------"

    cat > ~/.ssh/id_ed25519
    chmod 600 ~/.ssh/id_ed25519

	ssh-keygen -y -f ~/.ssh/id_ed25519 > ~/.ssh/id_ed25519.pub

	echo ""
    echo "--------------------------------------------------------"
    echo "PASTE GPG PRIVATE KEY BLOCK BELOW"
    echo "(Press Enter, paste the key, press Enter, then Ctrl+D)"
    echo "--------------------------------------------------------"

	gpg --batch --import

    yadm remote set-url origin "git@github.com:sakithb/dotfiles.git"

    echo "=== SSH and GPG complete ==="
fi

if ask "Setup secure boot"; then
    echo "=== Secure boot ==="

    if [[ "$(sbctl status --json | jq '.setup_mode')" = "true" ]]; then
        sudo sbctl create-keys
        sudo sbctl enroll-keys -m

        sudo sbctl verify --json \
                | jq '.[].file_name' \
                | xargs -n 1 sudo sbctl sign -s

        sudo sbctl sign -s \
            -o /usr/lib/systemd/boot/efi/systemd-bootx64.efi.signed \
            /usr/lib/systemd/boot/efi/systemd-bootx64.efi
    else
        echo "Please enter setup mode and retry"
        exit
    fi

    echo "=== Secure boot complete ==="
fi
