#!/usr/bin/env bash

THRESHOLD=20
BATTERY_PATH=$(upower -e | grep -E 'BAT|battery')
BATTERY_LEVEL=$(upower -i "$BATTERY_PATH" | awk '/percentage/ {gsub(/%/,""); print $2}')
BATTERY_STATE=$(upower -i "$BATTERY_PATH" | awk '/state/ {print $2}')

if [[ "$BATTERY_STATE" == "discharging" && "$BATTERY_LEVEL" -le "$THRESHOLD" ]]; then
    notify-send -u critical -p "Low Battery" "Battery is ${BATTERY_LEVEL}%."
fi
