pass_cmd = """spawn --userscript qute-pass -M gopass -d 'fuzzel -d'"""

# caret

config.bind("$", "move-to-end-of-line", mode="caret")
config.bind("0", "move-to-start-of-line", mode="caret")
config.bind("<Escape>", "mode-leave", mode="caret")
config.bind("<Return>", "yank selection", mode="caret")
config.bind("gg", "move-to-start-of-document", mode="caret")
config.bind("G", "move-to-end-of-document", mode="caret")
config.bind("H", "scroll left", mode="caret")
config.bind("J", "scroll down", mode="caret")
config.bind("K", "scroll up", mode="caret")
config.bind("L", "scroll right", mode="caret")
config.bind("V", "selection-toggle --line", mode="caret")
config.bind("Y", "yank selection -s", mode="caret")
config.bind("[", "move-to-start-of-prev-block", mode="caret")
config.bind("]", "move-to-start-of-next-block", mode="caret")
config.bind("b", "move-to-prev-word", mode="caret")
config.bind("e", "move-to-end-of-word", mode="caret")
config.bind("h", "move-to-prev-char", mode="caret")
config.bind("j", "move-to-next-line", mode="caret")
config.bind("k", "move-to-prev-line", mode="caret")
config.bind("l", "move-to-next-char", mode="caret")
config.bind("o", "selection-reverse", mode="caret")
config.bind("v", "selection-toggle", mode="caret")
config.bind("w", "move-to-next-word", mode="caret")
config.bind("y", "yank selection", mode="caret")
config.bind("{", "move-to-end-of-prev-block", mode="caret")
config.bind("}", "move-to-end-of-next-block", mode="caret")

# command

config.bind("<Alt-B>", "rl-backward-word", mode="command")
config.bind("<Alt-F>", "rl-forward-word", mode="command")
config.bind("<Ctrl-A>", "rl-beginning-of-line", mode="command")
config.bind("<Ctrl-E>", "rl-end-of-line", mode="command")
config.bind("<Ctrl-F>", "rl-forward-char", mode="command")
config.bind("<Ctrl-B>", "rl-backward-char", mode="command")
config.bind("<Ctrl-K>", "rl-kill-line", mode="command")
config.bind("<Alt-D>", "rl-kill-word", mode="command")
config.bind("<Alt-Backspace>", "rl-backward-kill-word", mode="command")
config.bind("<Ctrl-W>", "rl-filename-rubout", mode="command")
config.bind("<Ctrl-Shift-N>", "command-history-next", mode="command")
config.bind("<Ctrl-Shift-P>", "command-history-prev", mode="command")
config.bind("<Ctrl-Y>", "completion-item-yank", mode="command")
config.bind("<Ctrl-D>", "completion-item-del", mode="command")
config.bind("<Ctrl-Tab>", "completion-item-focus next-category", mode="command")
config.bind("<Ctrl-Shift-Tab>", "completion-item-focus prev-category", mode="command")
config.bind("<Ctrl-N>", "completion-item-focus next", mode="command")
config.bind("<Ctrl-P>", "completion-item-focus prev", mode="command")
config.bind("<PgDown>", "completion-item-focus next-page", mode="command")
config.bind("<PgUp>", "completion-item-focus prev-page", mode="command")
config.bind("<Return>", "command-accept", mode="command")
config.bind("<Ctrl-Return>", "command-accept --rapid", mode="command")
config.bind("<Escape>", "mode-leave", mode="command")

# hint

config.bind("<Ctrl-R>", "hint --rapid all tab", mode="hint")
config.bind("<Return>", "hint-follow", mode="hint")
config.bind("<Escape>", "mode-leave", mode="hint")

# insert

config.bind("<Ctrl-E>", "edit-text", mode="insert")
config.bind("<Ctrl-P>", pass_cmd, mode="insert")
config.bind("<Escape>", "mode-leave", mode="insert")
config.bind("<Shift-Escape>", "fake-key <Escape>", mode="insert")

# normal

config.bind(".", "cmd-repeat-last", mode="normal")
config.bind("/", "cmd-set-text /", mode="normal")
config.bind("?", "cmd-set-text ?", mode="normal")
config.bind(":", "cmd-set-text :", mode="normal")
config.bind("<Ctrl-F>", "scroll-page 0 1", mode="normal")
config.bind("<Ctrl-B>", "scroll-page 0 -1", mode="normal")
config.bind("<Ctrl-D>", "scroll-page 0 0.5", mode="normal")
config.bind("<Ctrl-U>", "scroll-page 0 -0.5", mode="normal")
config.bind("h", "scroll left", mode="normal")
config.bind("i", "mode-enter insert", mode="normal")
config.bind("j", "scroll down", mode="normal")
config.bind("k", "scroll up", mode="normal")
config.bind("l", "scroll right", mode="normal")
config.bind("q", "macro-record", mode="normal")
config.bind("@", "macro-run", mode="normal")
config.bind("n", "search-next", mode="normal")
config.bind("N", "search-prev", mode="normal")
config.bind("gg", "scroll-to-perc 0", mode="normal")
config.bind("G", "scroll-to-perc 100", mode="normal")
config.bind("v", "mode-enter caret", mode="normal")
config.bind("V", "mode-enter caret ;; selection-toggle --line", mode="normal")
config.bind("yy", "yank", mode="normal")
config.bind("<Escape>", "clear-keychain ;; search ;; fullscreen --leave", mode="normal")
config.bind("e", "cmd-set-text :open {url}", mode="normal")
config.bind("o", "cmd-set-text -s :open", mode="normal")
config.bind("O", "cmd-set-text -s :open -t", mode="normal")
config.bind("ds", "view-source", mode="normal")
config.bind("df", "devtools-focus", mode="normal")
config.bind("dd", "devtools", mode="normal")
config.bind("dh", "devtools left", mode="normal")
config.bind("dj", "devtools bottom", mode="normal")
config.bind("dk", "devtools top", mode="normal")
config.bind("dl", "devtools right", mode="normal")
config.bind("dw", "devtools window", mode="normal")
config.bind("ym", "yank inline [{title}]({url:yank})", mode="normal")
config.bind("yd", "yank domain", mode="normal")
config.bind("yp", "yank pretty-url", mode="normal")
config.bind("yt", "yank title", mode="normal")
config.bind("p", "mode-enter passthrough", mode="normal")
config.bind("<Return>", "selection-follow", mode="normal")
config.bind("f", "hint", mode="normal")
config.bind(";h", "hint all hover", mode="normal")
config.bind(";r", "hint --rapid all tab", mode="normal")
config.bind(";y", "hint links yank", mode="normal")
config.bind(";l", "hint links", mode="normal")
config.bind(";L", "hint links download", mode="normal")
config.bind(";i", "hint images", mode="normal")
config.bind(";I", "hint images download", mode="normal")
config.bind(";t", "hint inputs --first", mode="normal")
config.bind(";T", "hint inputs", mode="normal")
config.bind(";A", "hint all tab", mode="normal")
config.bind(";L", "hint links tab", mode="normal")
config.bind(";I", "hint images tab", mode="normal")
config.bind("t1", "tab-focus 1", mode="normal")
config.bind("t2", "tab-focus 2", mode="normal")
config.bind("t3", "tab-focus 3", mode="normal")
config.bind("t4", "tab-focus 4", mode="normal")
config.bind("t5", "tab-focus 5", mode="normal")
config.bind("t6", "tab-focus 6", mode="normal")
config.bind("t7", "tab-focus 7", mode="normal")
config.bind("t8", "tab-focus 8", mode="normal")
config.bind("t9", "tab-focus -1", mode="normal")
config.bind("tm", "tab-mute", mode="normal")
config.bind("tn", "tab-next", mode="normal")
config.bind("tp", "tab-prev", mode="normal")
config.bind("tt", "tab-focus last", mode="normal")
config.bind("tc", "open -t", mode="normal")
config.bind("td", "tab-close", mode="normal")
config.bind("tl", "forward", mode="normal")
config.bind("th", "back", mode="normal")
config.bind("tL", "forward -t", mode="normal")
config.bind("tH", "back -t", mode="normal")
config.bind("tu", "undo", mode="normal")
config.bind("tU", "undo -w", mode="normal")
config.bind("ta", "tab-only", mode="normal")
config.bind("tk", "tab-move +", mode="normal")
config.bind("tj", "tab-move -", mode="normal")
config.bind("ty", "tab-clone", mode="normal")
config.bind("tP", "open -- {clipboard}", mode="normal")
config.bind("tg", "tab-give", mode="normal")
config.bind("ts", "tab-pin", mode="normal")
config.bind("wc", "open -w", mode="normal")
config.bind("wp", "open -p", mode="normal")
config.bind("wq", "close", mode="normal")
config.bind("+", "zoom-in", mode="normal")
config.bind("-", "zoom-out", mode="normal")
config.bind("=", "zoom", mode="normal")
config.bind("r", "reload", mode="normal")
config.bind("c", "stop", mode="normal")
config.bind("R", "reload -f", mode="normal")
config.bind("F", "fullscreen", mode="normal")
config.bind("P", "print", mode="normal")
config.bind("gh", "history", mode="normal")
config.bind("gb", "bookmark-list", mode="normal")
config.bind("gs", "set", mode="normal")
config.bind("ds", "download-cancel", mode="normal")
config.bind("dc", "download-clear", mode="normal")
config.bind("bb", "bookmark-add -t", mode="normal")
config.bind("bq", "quickmark-save", mode="normal")
config.bind("sb", "cmd-set-text -s :bookmark-load", mode="normal")
config.bind("sq", "cmd-set-text -s :quickmark-load", mode="normal")
config.bind("st", "cmd-set-text -s :tab-select", mode="normal")
config.bind(",p", pass_cmd, mode="normal")

# passthrough

config.bind("<Shift-Escape>", "mode-leave", mode="passthrough")

# prompt

config.bind("<Alt-F>", "rl-forward-word", mode="prompt")
config.bind("<Alt-B>", "rl-backward-word", mode="prompt")
config.bind("<Ctrl-A>", "rl-beginning-of-line", mode="prompt")
config.bind("<Ctrl-E>", "rl-end-of-line", mode="prompt")
config.bind("<Ctrl-F>", "rl-forward-char", mode="prompt")
config.bind("<Ctrl-B>", "rl-backward-char", mode="prompt")
config.bind("<Alt-D>", "rl-kill-word", mode="prompt")
config.bind("<Alt-Backspace>", "rl-backward-kill-word", mode="prompt")
config.bind("<Ctrl-K>", "rl-kill-line", mode="prompt")
config.bind("<Ctrl-W>", "rl-filename-rubout", mode="prompt")
config.bind("<Alt-E>", "prompt-fileselect-external", mode="prompt")
config.bind("<Alt-P>", "prompt-open-download --pdfjs", mode="prompt")
config.bind("<Ctrl-X>", "prompt-open-download", mode="prompt")
config.bind("<Ctrl-N>", "prompt-item-focus next", mode="prompt")
config.bind("<Ctrl-P>", "prompt-item-focus prev", mode="prompt")
config.bind("<Return>", "prompt-accept", mode="prompt")
config.bind("<Escape>", "mode-leave", mode="prompt")

# register

config.bind("<Escape>", "mode-leave", mode="register")

# yesno

config.bind("<Escape>", "mode-leave", mode="yesno")
config.bind("<Return>", "prompt-accept", mode="yesno")
config.bind("N", "prompt-accept --save no", mode="yesno")
config.bind("Y", "prompt-accept --save yes", mode="yesno")
config.bind("n", "prompt-accept no", mode="yesno")
config.bind("y", "prompt-accept yes", mode="yesno")
