#!/usr/bin/env bash

prev_expr=""

while true; do
  expr=$(printf "" \
    | fuzzel \
        -d \
        -p "= " \
        -l 0 \
        --placeholder="$prev_expr" ) \
    || exit

  if [[ -z "$expr" ]]; then 
    break
  fi

  result=$(
    python3 -c "
import math
print(eval('${expr}', {'__builtins__':None, 'math':math}))
"
  )

  prev_expr="$expr = $result"
done
