#!/usr/bin/env bash

options="Shutdown\nReboot\nLock\nSuspend\nHibernate\nLogout"
chosen=$(echo -e "$options" | fuzzel -d)

case "$chosen" in
  Shutdown)
    systemctl poweroff
    ;;
  Reboot)
    systemctl reboot
    ;;
  Lock)
    loginctl lock-session
    ;;
  Suspend)
    systemctl suspend
    ;;
  Hibernate)
    systemctl hibernate
    ;;
  Logout)
    loginctl terminate-user $USER
    ;;
  *)
    ;;
esac
