#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(
      {
        find ~/projects/personal ~/projects/work ~/projects/other -mindepth 1 -maxdepth 1 -type d
        echo ~/scripts
      } | fzf
    )
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if [[ -z $TMUX && -z $(pgrep tmux) ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

tmux has-session -t=$selected_name 2> /dev/null

if [[ $? -eq 0 ]]; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t $selected_name
else
    tmux switch-client -t $selected_name
fi
