#!/usr/bin/env bash

dir="$HOME/Videos/screen-recordings"
mkdir -p "$dir"

path="$dir/$(date +"%d-%m-%Y-%H-%M-%S").mp4"

if [[ "$1" = "-s" ]]; then
    geometry="$(slurp)"
    wl-screenrec -f "$path" -g "$geometry" & PID=$!
else
    wl-screenrec -f "$path" & PID=$!
fi

notify-send -t 0 -A "default=Stop recording" "Recording has started" "Click to stop recording" 
kill $PID
